concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "TestRunner"
  url = "http://gitlab.training.com"
  id = 3
  token = "szZoHFntktuTAnTyWDzB"
  token_obtained_at = 2024-02-18T10:40:30Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"

[[runners]]
  name = "TestRunner02"
  url = "http://gitlab.training.com"
  id = 4
  token = "hS1xLidQPGyrnhevBsxa"
  token_obtained_at = 2024-02-18T12:08:57Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "http://gitlab.training.com"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "alpine:3.16.2"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
    network_mtu = 0
    network_mode = "gitlab-ci-ex_app_net"
    extra_hosts = ["gitlab.training.com:192.168.100.10"]
